services:
  chromadb:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/data

volumes:
  chroma_data:

# run these commands ----
# 1 - docker compose up -d -----Start the ChromaDB server for my RAG application
# 2 - docker ps ------ Is my ChromaDB container actually running?